// frontend-next/src/components/age-gate.tsx
'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useAppStore } from '@/stores/app-store';
import { modalOverlay, modalContent, shake } from '@/lib/animations';

export function AgeGate() {
  const { ageVerified, verifyAge } = useAppStore();
  const [birthDate, setBirthDate] = useState('');
  const [error, setError] = useState('');
  const [shouldShake, setShouldShake] = useState(false);

  if (ageVerified) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (!birthDate) {
      setError('Please enter your birthday');
      return;
    }

    const date = new Date(birthDate);
    if (isNaN(date.getTime())) {
      setError('Invalid date');
      return;
    }

    // Check if date is in the future
    if (date > new Date()) {
      setError('Birth date cannot be in the future');
      setShouldShake(true);
      setTimeout(() => setShouldShake(false), 500);
      return;
    }

    const isVerified = verifyAge(date);

    if (!isVerified) {
      setError('You must be 21 or older to enter');
      setShouldShake(true);
      setTimeout(() => setShouldShake(false), 500);
    }
  };

  return (
    <AnimatePresence>
      <motion.div
        variants={modalOverlay}
        initial="initial"
        animate="animate"
        exit="exit"
        className="fixed inset-0 z-[9999] bg-black/90 flex items-center justify-center p-4"
      >
        <motion.div
          variants={modalContent}
          initial="initial"
          animate="animate"
          exit="exit"
          className="w-full max-w-md"
        >
          <motion.div
            animate={shouldShake ? 'animate' : 'initial'}
            variants={shake}
            className="bg-win95-face border-[3px] border-win95-darkShadow shadow-[4px_4px_0px_#333]"
          >
            {/* Header with Logo */}
            <div className="bg-win95-shadow/30 p-4 md:p-6 border-b-[3px] border-win95-darkShadow text-center">
              <h1 className="text-2xl md:text-3xl font-display font-black tracking-tight">
                <span className="text-foe-accent drop-shadow-[2px_2px_0px_#333]">FOE</span>
                <span className="text-foreground drop-shadow-[2px_2px_0px_#a0a0a0]">FINDER</span>
              </h1>
            </div>

            {/* Content */}
            <div className="p-6 md:p-8">
              <h2 className="text-lg md:text-xl font-display font-black text-center uppercase tracking-[2px] md:tracking-[3px] mb-2">
                Age Verification
              </h2>
              <p className="text-sm text-muted-foreground text-center uppercase tracking-wide mb-6">
                You must be <strong className="text-foe-accent font-bold">21 or older</strong> to willingly enter a relationship disaster zone.
              </p>

              <form onSubmit={handleSubmit} className="space-y-6">
                <div>
                  <label
                    htmlFor="birthdate"
                    className="block text-xs font-bold uppercase tracking-wide mb-2 text-center"
                  >
                    Enter Your Birthday
                  </label>
                  <input
                    type="date"
                    id="birthdate"
                    value={birthDate}
                    onChange={(e) => {
                      setBirthDate(e.target.value);
                      setError('');
                    }}
                    className="w-full p-3 md:p-4 font-mono text-base bg-win95-shadow/30 border-[3px] border-win95-darkShadow text-center cursor-pointer focus:outline-none focus:border-foe-accent focus:ring-2 focus:ring-foe-accent"
                    max={new Date().toISOString().split('T')[0]}
                  />
                </div>

                {error && (
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="bg-foe-error/10 border-2 border-foe-error text-foe-error p-2 text-xs uppercase tracking-wide font-bold text-center"
                  >
                    {error}
                  </motion.div>
                )}

                <motion.button
                  type="submit"
                  disabled={!birthDate}
                  className="w-full p-3 md:p-4 bg-foe-accent text-foreground font-mono text-base font-bold uppercase tracking-[2px] border-[3px] border-win95-darkShadow shadow-[3px_3px_0px_#333] hover:bg-foe-accent/80 hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-[1px_1px_0px_#333] disabled:opacity-50 disabled:cursor-not-allowed disabled:bg-win95-shadow/30 transition-all duration-100"
                  whileTap={{ scale: 0.98 }}
                >
                  Proceed at Your Own Risk
                </motion.button>
              </form>

              <p className="text-[10px] text-muted-foreground text-center mt-6 uppercase tracking-wide">
                By entering, you accept full responsibility for all future arguments.
              </p>
            </div>
          </motion.div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}

// frontend/src/app/shared/components/age-gate.component.ts
import { Component, inject, signal, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AgeVerificationService } from '../../core/services/age-verification.service';

/**
 * Age Gate Component
 *
 * Displays a modal overlay requiring users to verify they are 21 or older.
 * Uses a date picker for birthday input and calculates age to verify eligibility.
 *
 * Verification is stored via AgeVerificationService:
 * - localStorage for anonymous users (same device persistence)
 * - Supabase profiles for logged-in users (cross-device persistence)
 */
@Component({
  selector: 'app-age-gate',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="age-gate-overlay">
      <div class="age-gate-modal">
        <div class="age-gate-header">
          <span class="logo-foe">FOE</span>
          <span class="logo-finder">FINDER</span>
        </div>

        <div class="age-gate-content">
          <h2 class="age-gate-title">AGE VERIFICATION</h2>
          <p class="age-gate-subtitle">
            You must be <strong>21 or older</strong> to willingly enter a relationship disaster zone.
          </p>

          <div class="birthday-input-group">
            <label for="birthday" class="birthday-label">ENTER YOUR BIRTHDAY</label>
            <input
              type="date"
              id="birthday"
              class="birthday-input"
              [max]="maxDate"
              [(ngModel)]="birthDate"
              (change)="onDateChange()"
            />
          </div>

          @if (errorMessage()) {
            <div class="error-message">
              {{ errorMessage() }}
            </div>
          }

          <button
            class="verify-btn"
            (click)="verifyAge()"
            [disabled]="!birthDate"
          >
            PROCEED AT YOUR OWN RISK
          </button>

          <p class="age-gate-disclaimer">
            By entering, you accept full responsibility for all future arguments.
          </p>
        </div>
      </div>
    </div>
  `,
  styles: [`
    /* =============================================
       AGE GATE - Mobile-First Responsive Styles
       ============================================= */

    .age-gate-overlay {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: rgba(0, 0, 0, 0.9);
      display: flex;
      justify-content: center;
      align-items: center;
      z-index: 9999;
      padding: var(--foe-space-md);
      font-family: 'Space Mono', monospace;
    }

    .age-gate-modal {
      background: var(--foe-bg-secondary);
      border: var(--foe-border-width-responsive) solid var(--foe-border);
      box-shadow: var(--foe-shadow-responsive);
      max-width: 400px;
      width: 100%;
      text-align: center;
    }

    @media (min-width: 768px) {
      .age-gate-modal {
        max-width: 450px;
      }
    }

    .age-gate-header {
      background: var(--foe-bg-tertiary);
      padding: var(--foe-space-md);
      border-bottom: 3px solid var(--foe-border);
      font-family: 'Inter', sans-serif;
      font-size: 24px;
      font-weight: 900;
      display: flex;
      justify-content: center;
      gap: 8px;
    }

    @media (min-width: 768px) {
      .age-gate-header {
        font-size: 32px;
        padding: var(--foe-space-lg);
        gap: 10px;
      }
    }

    .logo-foe {
      color: var(--foe-accent-primary);
      letter-spacing: -1px;
      text-shadow: 2px 2px 0px var(--foe-border);
    }

    .logo-finder {
      color: var(--foe-text-primary);
      font-weight: 700;
      letter-spacing: -1px;
      text-shadow: 2px 2px 0px var(--foe-bg-tertiary);
    }

    .age-gate-content {
      padding: var(--foe-space-lg);
    }

    @media (min-width: 768px) {
      .age-gate-content {
        padding: var(--foe-space-xl);
      }
    }

    .age-gate-title {
      font-family: 'Inter', sans-serif;
      font-size: var(--foe-text-lg);
      font-weight: 900;
      margin-bottom: var(--foe-space-sm);
      color: var(--foe-text-primary);
      text-transform: uppercase;
      letter-spacing: 2px;
    }

    @media (min-width: 768px) {
      .age-gate-title {
        font-size: var(--foe-text-xl);
        letter-spacing: 3px;
      }
    }

    .age-gate-subtitle {
      font-size: var(--foe-text-sm);
      color: var(--foe-text-secondary);
      margin-bottom: var(--foe-space-lg);
      text-transform: uppercase;
      letter-spacing: 1px;

      strong {
        color: var(--foe-accent-primary);
        font-weight: 700;
      }
    }

    .birthday-input-group {
      margin-bottom: var(--foe-space-lg);
    }

    .birthday-label {
      display: block;
      font-size: var(--foe-text-xs);
      font-weight: 700;
      color: var(--foe-text-primary);
      text-transform: uppercase;
      letter-spacing: 1px;
      margin-bottom: var(--foe-space-sm);
    }

    .birthday-input {
      width: 100%;
      padding: var(--foe-space-md);
      font-family: 'Space Mono', monospace;
      font-size: var(--foe-text-base);
      background: var(--foe-bg-tertiary);
      border: 3px solid var(--foe-border);
      color: var(--foe-text-primary);
      text-align: center;
      cursor: pointer;

      &:focus {
        outline: none;
        border-color: var(--foe-accent-primary);
        box-shadow: 0 0 0 2px var(--foe-accent-primary);
      }
    }

    .error-message {
      background: var(--foe-error-bg);
      border: 2px solid var(--foe-error);
      color: var(--foe-error);
      padding: var(--foe-space-sm);
      margin-bottom: var(--foe-space-md);
      font-size: var(--foe-text-xs);
      text-transform: uppercase;
      letter-spacing: 1px;
      font-weight: 700;
    }

    .verify-btn {
      width: 100%;
      padding: var(--foe-space-md);
      background: var(--foe-accent-primary);
      color: var(--foe-text-primary);
      font-family: 'Space Mono', monospace;
      font-size: var(--foe-text-base);
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 2px;
      border: 3px solid var(--foe-border);
      box-shadow: var(--foe-shadow-sm);
      cursor: pointer;
      transition: all 0.1s ease;

      &:hover:not(:disabled) {
        background: var(--foe-accent-light);
        transform: translate(2px, 2px);
        box-shadow: 1px 1px 0px var(--foe-border);
      }

      &:disabled {
        opacity: 0.5;
        cursor: not-allowed;
        background: var(--foe-bg-tertiary);
      }
    }

    .age-gate-disclaimer {
      margin-top: var(--foe-space-lg);
      font-size: 10px;
      color: var(--foe-text-muted);
      text-transform: uppercase;
      letter-spacing: 1px;
    }
  `]
})
export class AgeGateComponent {
  private ageVerificationService = inject(AgeVerificationService);

  @Output() verified = new EventEmitter<void>();

  birthDate: string = '';
  errorMessage = signal('');

  // Prevent future dates
  maxDate = new Date().toISOString().split('T')[0];

  onDateChange() {
    this.errorMessage.set('');
  }

  verifyAge() {
    if (!this.birthDate) {
      this.errorMessage.set('Please enter your birthday');
      return;
    }

    const isOldEnough = this.ageVerificationService.verifyAge(this.birthDate);

    if (isOldEnough) {
      // Also sync to Supabase if user happens to be logged in
      this.ageVerificationService.storeForCurrentUser();
      this.verified.emit();
    } else {
      this.errorMessage.set('You must be 21 or older to enter');
    }
  }
}
